spring.application.name=springvsquarkus

# Configuración de Resilience4j
resilience4j.timelimiter.instances.flakyPythonService.timeout-duration=3s
resilience4j.timelimiter.instances.flakyPythonService.cancel-running-future=true

resilience4j.retry.instances.flakyPythonService.max-attempts=3
resilience4j.retry.instances.flakyPythonService.wait-duration=1s

resilience4j.circuitbreaker.instances.flakyPythonService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.flakyPythonService.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.flakyPythonService.sliding-window-size=10
